### ISSUE TITLE
csswarp doesn't run on ie 11

### ISSUE THREAD

**Issue by HHGAG** [dirkweber/csswarp.js#5]
I haven't debugged yet, but it seems to be blocked on ie 11. No issues were logged to console.

**Comment by HHGAG** [comment]
Ok, here is the bug fix due changes of the user agent from ie11 from msie to trident

row 20:

```
    }else if(/msie/gi.test(userAgent)){
```

has to be

```
    }else if(/msie|trident/gi.test(userAgent)){
```

since last ie11 updates.

**Comment by dirkweber** [comment]
Sorry for the delay. Fixed for now.

**Comment by HHGAG** [comment]
:+1:
